const vocab = {
    "Common Phrases":[
        ["Hello","Habari","Pẹlẹ o","Nnọọ"],
        ["Goodbye","Kwaheri","O dabọ","Ka ọ dị"],
        ["Please","Tafadhali","Jowo","Biko"],
        ["Thank you","Asante","E dupe","Daalụ"],
        ["Sorry","Pole","Ma binu","Ndo"],
        ["Yes","Ndiyo","Bẹẹni","Ee"],
        ["No","Hapana","Rara","Mba"],
        ["Who?","Nani?","Tani?","Onye?"],
        ["What?","Nini?","Kini?","Kedu?"],
        ["When?","Lini?","Nigbawo?","Mgbe ole?"],
        ["Where?","Wapi?","Nibo?","Ebee?"],
        ["Why?","Kwa nini?","Kí nìdí?","Gịnị kpatara?"]
    ],
    "Places":[
        ["School","Shule","Ile-iwe","Ụlọ akwụkwọ"],
        ["Home","Nyumbani","Ile","Ụlọ"],
        ["Airport","Uwanja wa ndege","Papa ọkọ ofurufu","Ụgbọ elu"],
        ["Work","Kazi","Ṣiṣẹ","Ọrụ"],
        ["Office","Ofisi","Ọfiisi","Ụlọ ọrụ"],
        ["Store","Hifadhi","Itaja","Ụlọ ahịa"],
        ["Supermarket","Maduka makubwa","Ile ọja nla","Ụlọ ahịa"],
        ["Bank","Benki","Banki","Ụlọ akụ"],
        ["Library","Maktaba","Ile-ikawe","Ụlọ akwụkwọ"]
    ],
    "Family":[
        ["Man","Mwanaume","Okunrin","Nwoke"],
        ["Woman","Mwanamke","Obinrin","Nwanyị"],
        ["Boy","Kijana","Omokunrin","Nwa nwoke"],
        ["Girl","Msichana","Ọmọbinrin","Nwa agbọghọ"],
        ["Sibling","Ndugu","Arakunrin","Nwanne"],
        ["Dad","Baba","Baba","Nna"],
        ["Mom","Mama","Mama","Nne"],
        ["Parent","Mzazi","Òbí","Nne na nna"],
        ["Brother","Ndugu","Arakunrin","Nwanna"],
        ["Sister","Dada","Arabinrin","Nwanne"],
        ["Uncle","Mjomba","Aburo","Nwanne nna"],
        ["Aunt","Shangazi","Anti","Nne nne"],
        ["Cousin","Binamu","Omo iya","Nwa nwanne nna"],
        ["Grandpa","Babu","Bàbá àgbà","Nna nna"],
        ["Grandma","Bibi","Ìyá àgbà","Nne nne"]
    ],
    "People":[
        ["Friend","Rafiki","Ọrẹ","Enyi"],
        ["Neighbor","Jirani","Aladugbo","Agbata obi"],
        ["Boss","Bosi","Oga","Onye isi"],
        ["Employee","Mfanyakazi","Osise","Onye ọrụ"],
        ["Teacher","Mwalimu","Olukọ","Onye nkuzi"],
        ["Student","Mwanafunzi","Akeko","Nwa akwukwo"],
        ["Classmate","Mwanafunzi mwenza","Ọmọ kíláàsì","Nwa klas"],
        ["Doctor","Daktari","Dókítà","Dọkịta"],
        ["Nurse","Muuguzi","Nọọsi","Nọọsụ"],
        ["Mailman","Mtumaji barua","Oluranse","Onye ozi"],
    ],
    "Activities":[
        ["Bicycle","Baiskeli","Keke","Ịnyịnya igwe"],
        ["Basketball","Mpira wa Kikapu","Bọọlu inu agbọn","Bọọlụ basketball"],
        ["Football","Kandanda","Bọọlu afẹsẹgba","Egwuregwu bọọlụ"],
        ["Walk","Tembea","Rìn","Gaa ije"]
        ["Run","Kimbia","Ṣiṣe","Gbaa ọsọ"],
        ["Swim","Kuogelea","We","igwu mmiri"],
        ["Dance","Ngoma","Ijó","Agba egwu"],
        ["Play","Cheza","Ṣiṣẹ","Gwuo"],
        ["Sing","Imba","Kọrin","Abụ"],
        ["Game","Mchezo","Ere","Egwuregwu"],
        ["Videogame","Mchezo wa video","Ere fidio","Egwuregwu vidiyo"],
        ["Eat","Kula","Jẹun","Rie"],
        ["Sleep","Kulala","Sun","Ụra"],
        ["Read","Soma","Ka","Gụọ"],
        ["Book","Kitabu","Iwe","Akwụkwọ"]
    ],
    "Transporation":[
        ["Car","Gari","Ọkọ ayọkẹlẹ","Ụgbọ ala"],
        ["Bus","Basi","Ọkọ akero","Ụgbọ ala"],
        ["Plane","Ndege","Ofurufu","Ụgbọ elu"],
        ["Train","Treni","Reluwe","Ọzụzụ"],
        ["Bicycle","Baiskeli","Keke","Ịnyịnya igwe"]
    ],
    "Numbers and Time":[
        ["One","Moja","Ọkan","Otu"],
        ["Two","Mbili","Meji","Abụọ"],
        ["Three","Tatu","Mẹta","Atọ"],
        ["Four","Nne","Mẹrin","Anọ"],
        ["Five","Tano","Marun","Ise"],
        ["Six","Sita","Mefa","Isii"],
        ["Seven","Saba","Meje","Asaa"],
        ["Eight","Nane","Mẹjọ","Asato"],
        ["Nine","Tisa","Mẹsan","Itoolu"],
        ["Ten","Kumi","Mẹwa","Iri"],
        ["Eleven","Kumi na moja","Mọkanla","Iri na otu"],
        ["Twelve","Kumi na mbili","Mejila","Iri na abụọ"],
        ["Thirteen","Kumi na tatu","Mẹtala","Iri na ato"],
        ["Fourteen","Kumi na nne","Mẹrinla","Iri na anọ"],
        ["Fifteen","Kumi na tano","Meedogun","Iri na ise"],
        ["Sixteen","Kumi na sita","Mẹrindilogun","Iri na isii"],
        ["Seventeen","Kumi na saba","Mẹtadilogun","Iri na asaa"],
        ["Eighteen","Kumi na nane","Mejidilogun","Iri na asatọ"],
        ["Nineteen","Kumi na tisa","Mọkandilogun","Iri na itoolu"],
        ["Twenty","Ishirini","Ògún","Iri abụọ"],
        ["Winter","Majira ya baridi","Igba otutu","Oge oyi"],
        ["Spring","Masika","Orisun omi","Mmiri"],
        ["Summer","Majira ya joto","Igba ooru","N'oge okpomọkụ"],
        ["Autumn","Vuli","Isubu","Mgbụsị akwụkwọ"],
        ["Morning","Asubuhi","Owurọ","Ututu"],
        ["Afternoon","Mchana","Friday","N'ehihie"],
        ["Evening","Jioni","Irọlẹ","Mbubreyo"],
        ["Night","Usiku","Oru","Abali"]
    ],
    "School":[
        ["Student","Mwanafunzi","Omo ile iwe","Nwa akwukwo"],
        ["Teacher","Mwalimu","Olukọni","Onye nkuzi"],
        ["Homework","Kazi ya nyumbani","Iṣẹ amurele","Ọrụ ụlọ"],
        ["Exam","Mtihani","Idanwo","Ule"],
        ["Classmate","Mwanafunzi mwenza","Ọmọ kíláàsì","Nwa klas"],
        ["Library","Maktaba","Ile-ikawe","Ụlọ akwụkwọ"],
        ["Book","Kitabu","Iwe","Akwụkwọ"]
    ]
}