const vocab = {
    "Common Phrases":[
        ["Hello","Habari","Ẹ̀nlẹ̀ o","Nnọọ","Sannu"],
        ["Goodbye","Kwaheri","O dabọ","Ka ọ dị","Wallahi"],
        ["Please","Tafadhali","Jowo","Biko","Don Allah"],
        ["Thank you","Asante","E dupe","Daalụ","Na gode"],
        ["Sorry","Pole","E ma binu","Ndo","Yi hakuri"],
        ["Yes","Ndiyo","Bẹẹni","Ee","Ee"],
        ["No","Hapana","Rara","Mba","A'a"],
        ["Who","Nani","Tani","Onye","Wa"],
        ["What","Nini","Kini","Kedu","Menene"],
        ["When","Lini","Nigbawo","Mgbe ole","Yaushe"],
        ["Where","Wapi","Nibo","Ebee","Ina"],
        ["Why","Kwa nini","Kí nìdí","Gịnị kpatara","Me yasa"]
    ],
    "Places":[
        ["School","Shule","Ile-iwe","Ụlọ akwụkwọ","Makaranta"],
        ["Home","Nyumbani","Ile","Ụlọ","Gida"],
        ["Airport","Uwanja wa ndege","Papa ọkọ ofurufu","Ụgbọ elu","Filin jirgin sama"],
        ["Work","Kazi","Ṣiṣẹ","Ọrụ","Aiki"],
        ["Office","Ofisi","Ọfiisi","Ụlọ ọrụ","Ofishin"],
        ["Store","Hifadhi","Itaja","Ụlọ ahịa","Kantin"],
        ["Supermarket","Maduka makubwa","Ile ọja nla","Ụlọ ahịa","Babban kanti"],
        ["Bank","Benki","Banki","Ụlọ akụ","Banki"],
        ["Library","Maktaba","Ile-ikawe","Ụlọ akwụkwọ","Laburare"]
    ],
    "Family":[
        ["Man","Mwanaume","Okunrin","Nwoke","Mutum"],
        ["Woman","Mwanamke","Obinrin","Nwanyị","Mace"],
        ["Boy","Kijana","Omokunrin","Nwa nwoke","Yaro"],
        ["Girl","Msichana","Ọmọbinrin","Nwa agbọghọ","Yarinya"],
        ["Sibling","Ndugu","Arakunrin","Nwanne","Dan'uwa"],
        ["Dad","Baba","Baba","Nna","Baba"],
        ["Mom","Mama","Mama","Nne","Inna"],
        ["Parent","Mzazi","Òbí","Nne na nna","Iyaye"],
        ["Brother","Ndugu","Arakunrin","Nwanna","Dan'uwa"],
        ["Sister","Dada","Arabinrin","Nwanne","Yar'uwa"],
        ["Uncle","Mjomba","Aburo","Nwanne nna","Kawu"],
        ["Aunt","Shangazi","Anti","Nne nne","Goggo"],
        ["Cousin","Binamu","Omo iya","Nwa nwanne nna","Dan'uwa"],
        ["Grandpa","Babu","Bàbá àgbà","Nna nna","Kaka"],
        ["Grandma","Bibi","Ìyá àgbà","Nne nne","Kaka"]
    ],
    "People":[
        ["Friend","Rafiki","Ọrẹ","Enyi","Aboki"],
        ["Neighbor","Jirani","Aladugbo","Agbata obi","Makwabci"],
        ["Boss","Bosi","Oga","Onye isi","Shugaba"],
        ["Employee","Mfanyakazi","Osise","Onye ọrụ","Ma'aikaci"],
        ["Teacher","Mwalimu","Olukọ","Onye nkuzi","Malami"],
        ["Student","Mwanafunzi","Akeko","Nwa akwukwo","Dalibi"],
        ["Classmate","Mwanafunzi mwenza","Ọmọ kíláàsì","Nwa klas","Abokin karatu"],
        ["Doctor","Daktari","Dókítà","Dọkịta","Likita"],
        ["Nurse","Muuguzi","Nọọsi","Nọọsụ","Nurse"],
        ["Mailman","Mtumaji barua","Oluranse","Onye ozi","Mai aikawa"],
    ],
    "Activities":[
        ["Bicycle","Baiskeli","Keke","Ịnyịnya igwe","Keke"],
        ["Basketball","Mpira wa Kikapu","Bọọlu inu agbọn","Bọọlụ basketball","Kwallon kwando"],
        ["Football","Kandanda","Bọọlu afẹsẹgba","Egwuregwu bọọlụ","Kwallon kafa"],
        ["Walk","Tembea","Rìn","Gaa ije","Tafiya"],
        ["Run","Kimbia","Ṣiṣe","Gbaa ọsọ","Gudu"],
        ["Swim","Kuogelea","We","igwu mmiri","Yi iyo"],
        ["Dance","Ngoma","Ijó","Agba egwu","Rawa"],
        ["Play","Cheza","Ere","Gwuo","Wasa"],
        ["Sing","Imba","Kọrin","Abụ","Yi waƙa"],
        ["Game","Mchezo","Ere","Egwuregwu","Wasan"],
        ["Videogame","Mchezo wa video","Ere fidio","Egwuregwu vidiyo","Wasan Bidiyo"],
        ["Eat","Kula","Jẹun","Rie","Ku ci"],
        ["Sleep","Kulala","Sun","Ụra","Barci"],
        ["Read","Soma","Ka","Gụọ","Karanta"],
        ["Book","Kitabu","Iwe","Akwụkwọ","Littafi"]
    ],
    "Travel":[
        ["Car","Gari","Ọkọ ayọkẹlẹ","Ụgbọ ala","Mota"],
        ["Bus","Basi","Ọkọ akero","Ụgbọ ala","Bas"],
        ["Plane","Ndege","Ofurufu","Ụgbọ elu","Jirgin sama"],
        ["Train","Treni","Reluwe","Ọzụzụ","Jirgin kasa"],
        ["Bicycle","Baiskeli","Keke","Ịnyịnya igwe","Keke"]
    ],
    "Numbers and Time":[
        ["One","Moja","Ọkan","Otu","Daya"],
        ["Two","Mbili","Meji","Abụọ","Biyu"],
        ["Three","Tatu","Mẹta","Atọ","Uku"],
        ["Four","Nne","Mẹrin","Anọ","Hudu"],
        ["Five","Tano","Marun","Ise","Biyar"],
        ["Six","Sita","Mefa","Isii","Shida"],
        ["Seven","Saba","Meje","Asaa","Bakwai"],
        ["Eight","Nane","Mẹjọ","Asato","Takwas"],
        ["Nine","Tisa","Mẹsan","Itoolu","Tara"],
        ["Ten","Kumi","Mẹwa","Iri","Goma"],
        ["Eleven","Kumi na moja","Mọkanla","Iri na otu","Goma sha ɗaya"],
        ["Twelve","Kumi na mbili","Mejila","Iri na abụọ","Goma sha biyu"],
        ["Thirteen","Kumi na tatu","Mẹtala","Iri na ato","Goma sha uku"],
        ["Fourteen","Kumi na nne","Mẹrinla","Iri na anọ","Goma sha hudu"],
        ["Fifteen","Kumi na tano","Meedogun","Iri na ise","Goma sha biyar"],
        ["Sixteen","Kumi na sita","Mẹrindilogun","Iri na isii","Goma sha shida"],
        ["Seventeen","Kumi na saba","Mẹtadilogun","Iri na asaa","Goma sha bakwai"],
        ["Eighteen","Kumi na nane","Mejidilogun","Iri na asatọ","Goma sha takwas"],
        ["Nineteen","Kumi na tisa","Mọkandilogun","Iri na itoolu","Goma sha tara"],
        ["Twenty","Ishirini","Ògún","Iri abụọ","Ashirin"],
        ["Winter","Majira ya baridi","Igba otutu","Oge oyi","Hunturu"],
        ["Spring","Masika","Orisun omi","Mmiri","Bazara"],
        ["Summer","Majira ya joto","Igba ooru","N'oge okpomọkụ","Damina"],
        ["Autumn","Vuli","Isubu","Mgbụsị akwụkwọ","Kaka"],
        ["Morning","Asubuhi","Owurọ","Ututu","Safiya"],
        ["Afternoon","Mchana","Ọsan","N'ehihie","La'asar"],
        ["Evening","Jioni","Irọlẹ","Mbubreyo","Maraice"],
        ["Night","Usiku","Oru","Abali","Dare"]
    ],
    "School":[
        ["Student","Mwanafunzi","Omo ile iwe","Nwa akwukwo","Dalibi"],
        ["Teacher","Mwalimu","Olukọni","Onye nkuzi","Malami"],
        ["Homework","Kazi ya nyumbani","Iṣẹ amurele","Ọrụ ụlọ","Aikin gida"],
        ["Exam","Mtihani","Idanwo","Ule","Jarrabawa"],
        ["Classmate","Mwanafunzi mwenza","Ọmọ kíláàsì","Nwa klas","Abokin karatu"],
        ["Library","Maktaba","Ile-ikawe","Ụlọ akwụkwọ","Laburare"],
        ["Book","Kitabu","Iwe","Akwụkwọ","Littafi"]
    ]
}